export type Service = {
  slug: string;
  title: string;
  category: string;
  shortDescription: string;
  description: string;
  outcomes: string[];
  useCases: string[];
};

export const services: Service[] = [
  {
    slug: "ai-strategy",
    title: "AI Strategy",
    category: "AI Transformation",
    shortDescription: "Turn AI ambition into a practical, prioritized business roadmap.",
    description: "Syncrio helps organizations identify high-value AI opportunities, prioritize initiatives, define an adoption roadmap, and connect AI investments to measurable business outcomes.",
    outcomes: ["Prioritized AI opportunity roadmap", "Business-aligned use cases", "Investment and adoption priorities"],
    useCases: ["AI opportunity discovery", "Enterprise AI roadmaps", "Use-case prioritization", "AI operating-model planning"],
  },
  {
    slug: "ai-governance",
    title: "AI Governance",
    category: "AI Transformation",
    shortDescription: "Build responsible, scalable guardrails for enterprise AI adoption.",
    description: "Syncrio helps teams establish practical governance for AI initiatives, including accountability, risk controls, human oversight, standards, and lifecycle management.",
    outcomes: ["Clear AI accountability", "Practical risk controls", "Scalable governance standards"],
    useCases: ["AI governance frameworks", "Responsible AI controls", "AI risk assessment", "Human-in-the-loop design"],
  },
  {
    slug: "enterprise-ai",
    title: "Enterprise AI",
    category: "AI Transformation",
    shortDescription: "Move AI from experimentation into enterprise workflows and operations.",
    description: "Syncrio helps enterprises identify, design, and operationalize AI capabilities across business and delivery functions while keeping transformation aligned with enterprise needs.",
    outcomes: ["Production-oriented AI roadmap", "Enterprise workflow integration", "Measurable transformation priorities"],
    useCases: ["Enterprise AI adoption", "AI operating models", "AI-enabled delivery", "Cross-functional AI transformation"],
  },
  {
    slug: "ai-agents",
    title: "AI Agents",
    category: "AI Transformation",
    shortDescription: "Design intelligent agents that can reason, coordinate, and act across enterprise workflows.",
    description: "Syncrio helps organizations identify agentic use cases and design AI agents that support knowledge work, workflow execution, decision support, and enterprise operations.",
    outcomes: ["High-value agent opportunities", "Agent workflow designs", "Human and AI collaboration models"],
    useCases: ["Workflow agents", "Research and knowledge agents", "Delivery agents", "Decision-support agents"],
  },
  {
    slug: "genai-adoption",
    title: "Generative AI Adoption",
    category: "AI Transformation",
    shortDescription: "Help teams move from GenAI experimentation to repeatable business value.",
    description: "Syncrio helps organizations select practical generative AI use cases, prepare teams, establish adoption patterns, and scale successful experiments into everyday workflows.",
    outcomes: ["Focused GenAI use cases", "Adoption roadmap", "Repeatable usage patterns"],
    useCases: ["GenAI workshops", "Use-case discovery", "Prompt and workflow adoption", "Enterprise GenAI enablement"],
  },
  {
    slug: "ai-copilots",
    title: "AI Copilots",
    category: "AI Transformation",
    shortDescription: "Create AI assistants that augment people with contextual knowledge and workflow support.",
    description: "Syncrio helps teams design copilots around real roles, business knowledge, and workflows so employees can access insights and complete work more efficiently.",
    outcomes: ["Role-specific copilots", "Knowledge-assisted workflows", "Improved employee productivity"],
    useCases: ["Delivery copilots", "Knowledge copilots", "Operations assistants", "Decision-support assistants"],
  },
  {
    slug: "pmo",
    title: "PMO",
    category: "Project & Program Management",
    shortDescription: "Strengthen project governance, visibility, cadence, and delivery discipline.",
    description: "Syncrio provides practical PMO capabilities to improve governance, reporting, decision-making, dependencies, and delivery consistency across complex programs.",
    outcomes: ["Better portfolio visibility", "Consistent governance cadence", "Clearer delivery accountability"],
    useCases: ["PMO setup", "Governance models", "Executive reporting", "Delivery operating rhythms"],
  },
  {
    slug: "delivery-excellence",
    title: "Delivery Excellence",
    category: "Project & Program Management",
    shortDescription: "Make enterprise delivery more predictable, measurable, and outcome-focused.",
    description: "Syncrio helps organizations improve delivery practices, metrics, governance, and execution discipline across complex transformation programs.",
    outcomes: ["Predictable delivery", "Improved execution visibility", "Outcome-focused governance"],
    useCases: ["Delivery health assessments", "Delivery frameworks", "Performance metrics", "Transformation delivery"],
  },
  {
    slug: "portfolio-governance",
    title: "Portfolio Governance",
    category: "Project & Program Management",
    shortDescription: "Bring strategic priorities, investments, risks, and delivery into one governance model.",
    description: "Syncrio helps leadership teams create portfolio governance that improves prioritization, investment visibility, dependencies, and executive decision-making.",
    outcomes: ["Portfolio-level visibility", "Stronger prioritization", "Faster executive decisions"],
    useCases: ["Portfolio reviews", "Investment prioritization", "Dependency management", "Executive governance"],
  },
  {
    slug: "agile-transformation",
    title: "Agile Transformation",
    category: "Project & Program Management",
    shortDescription: "Improve how teams plan, collaborate, deliver, and continuously adapt.",
    description: "Syncrio helps organizations apply pragmatic agile practices that fit their operating environment rather than forcing a one-size-fits-all framework.",
    outcomes: ["Faster feedback cycles", "Improved team alignment", "More adaptive delivery"],
    useCases: ["Agile operating models", "Ways-of-working design", "Team enablement", "Scaled delivery improvement"],
  },
  {
    slug: "risk-management",
    title: "Risk Management",
    category: "Project & Program Management",
    shortDescription: "Identify, prioritize, and actively manage delivery risks before they become blockers.",
    description: "Syncrio helps transformation teams establish practical risk and issue management with clear ownership, escalation paths, and decision support.",
    outcomes: ["Earlier risk visibility", "Clear ownership", "Faster mitigation decisions"],
    useCases: ["Program risk reviews", "Issue management", "Escalation models", "Risk dashboards"],
  },
  {
    slug: "program-leadership",
    title: "Program Leadership",
    category: "Project & Program Management",
    shortDescription: "Bring experienced leadership to complex enterprise transformation programs.",
    description: "Syncrio provides program leadership focused on outcomes, stakeholder alignment, execution discipline, and navigating complex transformation environments.",
    outcomes: ["Aligned stakeholders", "Stronger execution", "Outcome-oriented leadership"],
    useCases: ["Transformation leadership", "Program recovery", "Executive alignment", "Complex delivery management"],
  },
  {
    slug: "workflow-automation",
    title: "Workflow Automation",
    category: "Intelligent Automation",
    shortDescription: "Connect people, systems, and AI to reduce repetitive workflow effort.",
    description: "Syncrio helps organizations identify and automate workflow steps using integrations, rules, AI, and human approvals where they add value.",
    outcomes: ["Reduced manual effort", "Faster cycle times", "More consistent workflows"],
    useCases: ["Approval workflows", "Cross-system automation", "AI-assisted workflows", "Operational handoffs"],
  },
  {
    slug: "testing-automation",
    title: "Testing Automation",
    category: "Intelligent Automation",
    shortDescription: "Accelerate quality engineering with intelligent test automation and validation.",
    description: "Syncrio helps delivery teams automate quality activities, improve coverage, and use AI to accelerate test design, validation, and defect analysis.",
    outcomes: ["Faster test cycles", "Improved coverage", "Reduced repetitive QA effort"],
    useCases: ["Test automation", "AI-assisted test generation", "Regression testing", "Quality validation"],
  },
  {
    slug: "business-automation",
    title: "Business Automation",
    category: "Intelligent Automation",
    shortDescription: "Automate business activities that consume time without creating strategic value.",
    description: "Syncrio helps teams redesign and automate business processes while keeping people in control of decisions that require judgment.",
    outcomes: ["Lower operational effort", "Faster processing", "More consistent execution"],
    useCases: ["Operations automation", "Back-office workflows", "Service processes", "Decision-support automation"],
  },
  {
    slug: "document-intelligence",
    title: "Document Intelligence",
    category: "Intelligent Automation",
    shortDescription: "Turn unstructured documents into usable data, insights, and automated actions.",
    description: "Syncrio helps organizations extract, classify, summarize, validate, and route information from business documents using intelligent automation and AI.",
    outcomes: ["Faster document processing", "Reduced manual extraction", "Structured business information"],
    useCases: ["Document extraction", "Contract and form processing", "Document classification", "AI summarization"],
  },
  {
    slug: "process-automation",
    title: "Process Automation",
    category: "Intelligent Automation",
    shortDescription: "Redesign and automate end-to-end business processes for measurable efficiency.",
    description: "Syncrio combines process analysis, automation, AI, and workflow design to improve how work moves across teams and systems.",
    outcomes: ["Shorter process cycles", "Lower manual workload", "Improved process consistency"],
    useCases: ["Process discovery", "End-to-end automation", "Exception handling", "Process optimization"],
  },
  {
    slug: "digital-transformation",
    title: "Digital Transformation",
    category: "Enterprise Consulting",
    shortDescription: "Connect technology, processes, people, and operating priorities into one transformation agenda.",
    description: "Syncrio helps organizations plan and execute digital transformation with a business-first approach that connects strategy to practical delivery.",
    outcomes: ["Clear transformation roadmap", "Aligned technology and business priorities", "Stronger execution"],
    useCases: ["Transformation strategy", "Digital operating models", "Enterprise modernization", "Transformation roadmaps"],
  },
  {
    slug: "operating-model",
    title: "Operating Model",
    category: "Enterprise Consulting",
    shortDescription: "Design operating models that make transformation sustainable and scalable.",
    description: "Syncrio helps organizations define roles, governance, processes, capabilities, and ways of working that support strategic transformation goals.",
    outcomes: ["Clear accountability", "Scalable ways of working", "Better organizational alignment"],
    useCases: ["Target operating models", "AI operating models", "Governance design", "Capability planning"],
  },
  {
    slug: "technology-strategy",
    title: "Technology Strategy",
    category: "Enterprise Consulting",
    shortDescription: "Translate business priorities into practical technology and platform decisions.",
    description: "Syncrio helps leadership teams evaluate technology priorities, architecture considerations, integration needs, and transformation sequencing.",
    outcomes: ["Technology roadmap", "Better investment decisions", "Business-technology alignment"],
    useCases: ["Technology roadmaps", "Platform strategy", "Integration planning", "Modernization priorities"],
  },
  {
    slug: "process-excellence",
    title: "Process Excellence",
    category: "Enterprise Consulting",
    shortDescription: "Improve processes before automating them so technology delivers lasting value.",
    description: "Syncrio helps teams understand current processes, remove unnecessary complexity, standardize execution, and identify opportunities for automation and AI.",
    outcomes: ["Simpler processes", "Reduced process variation", "Better automation readiness"],
    useCases: ["Process assessment", "Process redesign", "Standardization", "Automation opportunity discovery"],
  },
  {
    slug: "organizational-change",
    title: "Organizational Change",
    category: "Enterprise Consulting",
    shortDescription: "Help people adopt new technology, processes, and AI-enabled ways of working.",
    description: "Syncrio helps organizations prepare teams for transformation through stakeholder alignment, communication, enablement, adoption planning, and change measurement.",
    outcomes: ["Higher adoption", "Better stakeholder alignment", "Sustainable transformation"],
    useCases: ["AI adoption", "Change impact assessment", "Training and enablement", "Stakeholder engagement"],
  },
];

export const servicesBySlug = Object.fromEntries(services.map((service) => [service.slug, service])) as Record<string, Service>;

export const serviceCategories = Array.from(new Set(services.map((service) => service.category)));
