const disciplines=[['◈','AI Transformation',['AI Strategy','AI Governance','Enterprise AI','AI Agents','GenAI Adoption','Copilots']],['▣','Project & Program Management',['PMO','Delivery Excellence','Portfolio Governance','Agile Transformation','Risk Management','Program Leadership']],['⌁','Intelligent Automation',['Workflow Automation','Testing Automation','Business Automation','Document Intelligence','AI Agents','Process Automation']],['◎','Enterprise Consulting',['Digital Transformation','Operating Model','Technology Strategy','Process Excellence','Organizational Change']]];
const products=[['Meeting Intelligence','Syncrio Lens','Capture action items, decisions, risks, and organizational knowledge from every meeting.',['Action Items','Knowledge Capture','Risk Detection']],['Quality Engineering','TestPilot AI','AI-driven requirements traceability, test case generation, and execution planning at enterprise scale.',['Requirements Traceability','Test Case Generation','Execution Planning']],['Enterprise Knowledge Graph','Knowledge Hub','Unify SOPs, docs, and delivery artifacts into a searchable, copilot-ready knowledge layer.',['SOP Search','AI Copilot','Delivery Copilot']]];
const industries=['Procurement','Manufacturing','Healthcare','Retail','Financial Services','Technology','Energy'];
const steps=['Discover','Assess','Design','Implement','Optimize','Scale'];
const stepText=['Understand delivery challenges, portfolio, and operating context.','Benchmark AI, automation, and program maturity against enterprise leaders.','Architect a transformation roadmap with measurable business outcomes.','Deliver AI, automation, and PMO capabilities with our specialist teams.','Instrument, measure, and improve delivery velocity and quality.','Extend across portfolios, geographies, and business units.'];
document.querySelector('#disciplines').innerHTML=disciplines.map(([icon,title,items])=>`<article class="card"><div class="cardIcon">${icon}</div><h3>${title}</h3><ul>${items.map(i=>`<li><span>✓</span>${i}</li>`).join('')}</ul></article>`).join('');
document.querySelector('#productCards').innerHTML=products.map(([eyebrow,title,text,tags])=>`<article class="product card"><p class="mini">${eyebrow}</p><h3>${title}</h3><p>${text}</p><div>${tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div><b>Coming soon</b></article>`).join('');
document.querySelector('#industryGrid').innerHTML=industries.map(i=>`<a><span>✦</span>${i}<small>›</small></a>`).join('');
document.querySelector('#timeline').innerHTML=steps.map((s,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h3>${s}</h3><p>${stepText[i]}</p></article>`).join('');
